### ISSUE TITLE
Kit Internals

### ISSUE THREAD

**Issue by ninjafrostpn** [sourcebots/volunteer-docs#21]

**Comment by ninjafrostpn** [comment]
Not really required, as the kit docs cover this anyways...

**Comment by RealOrangeOne** [comment]
I disagree. I think this is worth including. The docs shows some details on how to the public API of it works, but nothing on the internals of how the Pi's services work, such as those covered in @Adimote 's presentations.

**Comment by RealOrangeOne** [comment]
My suggestion is in fact covered by https://github.com/sourcebots/volunteer-docs/issues/18, woops!
