### ISSUE TITLE
.spelling file format

### ISSUE THREAD

**Issue by nmalky** [sourcebots/volunteer-docs#22]
Discussion on how this should be formatted:
- categorised vs alphabetical
- 

There isn't any documentation anywhere for this.
This is adding extra complexity.
@Tyler-Ward @Adimote

**Comment by trickeydan** [comment]
I think we should discuss this further in depth at a meeting. There are arguments for both approaches:

## Categorised
- Easy to find words
- Possible disagreements over what categories some words fit in.
- I would say that this is less confusing in general

## Alphabetical
- @Adimote has written a script to auto sort them
- Reduces merge conflicts
- In line with our other web repositories

**Comment by RealOrangeOne** [comment]
I would argue that Categorised isnt easier to find words. Yes it's easier to find the word you don't know how to spell, but it's a lot harder to find an entry if you need to edit it or whatever. 

I'm not sure this needs much discussion, from that list there's almost no benefits to categorised, and many for alphabetically, not to mention it's trivial to check alphabetical, and it's the same as all our repos
